# Generated by Django 4.2.7 on 2025-11-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("employee_id", models.CharField(max_length=10, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("MEMBER", "メンバー"), ("SHACHOU_SHITSU", "社長室")],
                        default="MEMBER",
                        max_length=20,
                    ),
                ),
                ("is_rotation_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "speech_type",
                    models.CharField(
                        choices=[("BUSINESS", "業務"), ("THREE_MIN", "３分間")],
                        max_length=20,
                    ),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "assigned_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_calendar_event_id",
                    models.CharField(max_length=200, unique=True),
                ),
                ("calendar_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.scheduleentry",
                    ),
                ),
            ],
        ),
    ]
