# Generated by Django 4.2.7 on 2025-11-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_order_gyomu"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleentry",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
