# Generated by Django 4.2.7 on 2025-12-01 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_scheduleentry_google_event_id_scheduleentry_is_sent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyEventBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entries",
                to="core.monthlyeventbatch",
            ),
        ),
    ]
